version: 2.1

jobs:
  build:
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run lint

workflows:
  version: 2
  executor:
    name: node/default
    tag: "14.7"
  build:
    jobs:
      - build
