version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  lint:
    executor:
      name: node/default
      tag: "14.7"
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run lint
