version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-npm
      - run: npm install
      - run: npm run lint

workflows:
  version: 2
  build:
    jobs:
      - build
