version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node@3.0.0
    steps:
      - checkout
      - run: npm install
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: npm run test:coverage
      - store_artifacts:
          path: coverage
