version: 2.1

jobs:
  build:
    executor:
      name: node/default
      tag: "14.7"
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run lint

workflows:
  version: 2
  build:
    jobs:
      - build
