name: deploy

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint
      - name: Run test coverage
        run: npm run test:coverage
      - name: Deploy codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/coverage-final.json
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true
      - name: Run build document
        run: npm run doc
      - name: Deploy document
        uses: Cecilapp/GitHub-Pages-deploy@master
        env:
          EMAIL: mochen.china@gmail.com
          GH_TOKEN: ${{ secrets.CI_GH_PAGE_TOKEN }}
          BUILD_DIR: doc
